spring.application.name=solardocs-backend
server.port=8080

# Set SOLARDOCS_DATA_DIR for installed deployments.
solardocs.data-dir=${SOLARDOCS_DATA_DIR:./solardocs-data}

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

logging.file.name=${solardocs.data-dir}/Logs/solardocs.log
logging.level.com.solardocs=DEBUG
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
